package testCases;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import pageObjects.HomePage;
import pageObjects.LoginPage;
import pageObjects.Carrier.CarrierPage;
import pageObjects.Carrier.CreateCarrierPage;

public class CarrierTest extends WebDriverTestBase {
	WebDriver driver;
	LoginPage onLoginPage;
	HomePage onHomePage;
	CarrierPage onCarrierPage ;
	CreateCarrierPage onCreateCarrierPage;
	String user = "admin@mailinator.com";
	String pass = "admin";
	String carrierName = "AutoGenerated";
	
	@Test (priority = 0)
	public void CreateCarrierTest() {
		
		onLoginPage = PageFactory.initElements(driver, LoginPage.class);
		onLoginPage.open();
		onHomePage = onLoginPage.LoginAsAdmin(user, pass);
		onCarrierPage = onHomePage.clickOnCarrier();
		onCreateCarrierPage =  onCarrierPage.createCarrier();
		onCarrierPage = onCreateCarrierPage.completeAllFields(carrierName);
		Assert.assertTrue(onCarrierPage.getMessage().contains("created"), "Carrier was successfully created.");
	}
	
	@Test (priority = 1)
	public void ModifyCarrierTest() {
		
		onLoginPage = PageFactory.initElements(driver, LoginPage.class);
		onLoginPage.open();
		onHomePage = onLoginPage.LoginAsAdmin(user, pass);
		onCarrierPage = onHomePage.clickOnCarrier();
		onCreateCarrierPage = onCarrierPage.EditCarrier(carrierName);
		onCarrierPage = onCreateCarrierPage.editCarrier();
		Assert.assertTrue(onCarrierPage.getMessage().contains("saved"), "Carrier was successfully saved.");
		}

	@Test (priority = 2)
	public void DeleteCarrierTest() {
		
		onLoginPage = PageFactory.initElements(driver, LoginPage.class);
		onLoginPage.open();
		onHomePage = onLoginPage.LoginAsAdmin(user, pass);
		onCarrierPage = onHomePage.clickOnCarrier();
		onCarrierPage.deleteCarrier(carrierName);
		Assert.assertTrue(onCarrierPage.getMessage().contains("delete"), "Record was successfully deleted. ");
	}
	
	@BeforeMethod
	public void setUp () {
		driver = new FirefoxDriver ();
		driver.manage().window().maximize();
	}
	
	@AfterMethod
	    public void tearDown() {
		//logout
		driver.findElement(By.xpath("/html/body/div/nav/div[2]/div/a/span")).click();
		driver.findElement(By.xpath("/html/body/div/nav/div[2]/div/ul/li/a")).click();
		driver.quit();
	    
	    }

}
